---
title: "Random Forest"
author: "Anushka Kapoor"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
```


```{r}
load("~/Desktop/MSBA Class'24/Machinelearning/MachineLearning/returns_sp500.RData")
ticker <- "AAPL"
data <- returns_sp500 %>% filter(Ticker == ticker, Date >= "2022-06-24")
total_data <- data[, c("Date", "Open", "High", "Low", "Close", "Movement")]
```


```{r}
set.seed(7)
total_obs <- dim(total_data)[1]
# Data partition / Sample splitting
train_data_indices <- sample(1:total_obs, 0.8*total_obs)
train_data <- total_data[train_data_indices,]
test_data <- total_data[-train_data_indices,]
# Record the size of training data and test data
train_obs <- dim(train_data)[1]
test_obs <- dim(test_data)[1]
#total_data$Movement <- as.factor(total_data$Movement)
```

```{r}
library(randomForest)
set.seed(222)
rf_model <- randomForest(Close ~., data = train_data, ntree=2000, mtry=4, importance=T)

predictions <- predict(rf_model, newdata = test_data)

#rf_pred <- predict(rf_mod, newdata = test_data)
rf_mse <- mean((predictions - test_data$Close)^2)
rf_rsquared <- 1 - rf_model$mse / var(test_data$Close)

mae <- mean(abs(predictions - test_data$Close))
rmse <- sqrt(rf_mse)

```

```{r}
plot(test_data$Date, test_data$Close, type = "l", col = "blue", lwd = 2, main = "Actual vs Predicted Values", xlab = "Date", ylab = "Values")
lines(test_data$Date, predictions, col = "red", lwd = 2)
legend("topleft", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1, lwd = 2)
```

```{r}
set.seed(222)
rf_model1 <- randomForest(Close ~ Open + High + Low + Movement, data = train_data, ntree=1000, mtry=1)

predictions1 <- predict(rf_model1, newdata = test_data)

#rf_pred <- predict(rf_mod, newdata = test_data)
rf_mse1 <- mean((predictions1 - test_data$Close)^2)
rf_rsquared1 <- 1 - rf_model1$mse / var(test_data$Close)

mae1 <- mean(abs(predictions1 - test_data$Close))
rmse1 <- sqrt(rf_mse1)
```

```{r}
plot(test_data$Date, test_data$Close, type = "l", col = "blue", lwd = 2, main = "Actual vs Predicted Values", xlab = "Date", ylab = "Values")
lines(test_data$Date, predictions1, col = "red", lwd = 2)
legend("topright", legend = c("Actual", "Predicted"), col = c("blue", "red"), lty = 1, lwd = 2)
```

